
name: Publish Python ðŸ distributions ðŸ“¦ to PyPI and TestPyPI

on: push

jobs:
  build-n-publish:
    name: Build and publish Python ðŸ distributions ðŸ“¦ to PyPI and TestPyPI
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Setup virtual environment
      run: |
        pip install --upgrade pip
        python3.8 -m venv env
        source env/bin/activate
        echo "VIRTUAL ENV:" $VIRTUAL_ENV
    - name: Install Cmake
      run: >-
        sudo apt-get install cmake
    - name: check directory content
      run: |
        cd env/lib
        ls
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Install cibuildwheel
      run: |
        ls 
        source env/bin/activate
        python -m pip install cibuildwheel==2.4.0
        
    - name: Install boost
      if: ${{ runner.os == 'Windows' || runner.os == 'macOS' }}
      uses: MarkusJx/install-boost@v2.1.0
      id: install-boost
      with:
        boost_version: 1.76.0
        boost_install_dir: ${{ matrix.boost_install_dir }}

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.3.1
      env:
        # Specify which Python versions to build wheels
        # https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip
        CIBW_BUILD: "cp36-* cp37-* cp38-* cp39-*"
        # Skip 32 bit architectures, musllinux, and i686
        CIBW_SKIP: "*-win32 *-musllinux_x86_64 *_i686"
        CIBW_BEFORE_BUILD: python -m pip install cmake
        CIBW_BEFORE_BUILD_LINUX: echo $BOOST_ROOT
        CIBW_BEFORE_ALL_LINUX: >
          yum install -y wget &&
          cd / &&  mkdir boost && cd boost &&
          wget --no-check-certificate 'https://sourceforge.net/projects/boost/files/boost/1.76.0/boost_1_76_0.tar.bz2' && 
          tar xf boost_1_76_0.tar.bz2 &&
          cd {package}
        CIBW_TEST_COMMAND: python -m pytest --rootdir={package} {package}
        CIBW_TEST_REQUIRES: pytest
        CIBW_ENVIRONMENT_WINDOWS: BOOST_ROOT='${{ steps.install-boost.outputs.BOOST_ROOT }}'
        CIBW_ENVIRONMENT_MACOS: BOOST_ROOT='${{ steps.install-boost.outputs.BOOST_ROOT }}'
        CIBW_ENVIRONMENT_LINUX: BOOST_ROOT=/boost
        CIBW_ENVIRONMENT_PASS_LINUX: BOOST_ROOT
          
    - name: check directory content
      run: |
        ls
    - name: Publish distribution ðŸ“¦ to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution ðŸ“¦ to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
